// Constants for Trainee Application Form

export const TITLES = [
  { value: 'Dr.', label: 'Dr.' },
  { value: 'Mr.', label: 'Mr.' },
  { value: 'Mrs.', label: 'Mrs.' },
  { value: 'Ms.', label: 'Ms.' },
  { value: 'Mx.', label: 'Mx.' },
];

export const SKILLS_ACQUIRED = [
  'Active Listening',
  'Empathy and Compassion',
  'Crisis Intervention',
  'Assessment and Evaluation',
  'Treatment Planning',
  'Cognitive Behavioral Techniques',
  'Mindfulness-Based Interventions',
  'Group Therapy Facilitation',
  'Family Systems Therapy',
  'Trauma-Informed Care',
  'Motivational Interviewing',
  'Solution-Focused Therapy',
  'Psychoeducation',
  'Boundary Setting',
  'Cultural Competency',
  'Ethical Decision Making',
  'Documentation and Record Keeping',
  'Suicide Risk Assessment',
  'Substance Abuse Counseling',
  'Grief and Loss Counseling',
];

export const SPECIALTIES = [
  'Anxiety Disorders',
  'Depression',
  'PTSD and Trauma',
  'Bipolar Disorder',
  'ADHD',
  'Autism Spectrum Disorders',
  'Eating Disorders',
  'Substance Abuse',
  'Addiction Recovery',
  'Grief and Loss',
  'Relationship Issues',
  'Couples Therapy',
  'Family Therapy',
  'LGBTQ+ Issues',
  'Identity and Self-Esteem',
  'Life Transitions',
  'Workplace Stress',
  'Academic Stress',
  'Parenting Issues',
  'Anger Management',
  'Social Anxiety',
  'Panic Disorders',
  'OCD',
  'Phobias',
  'Sleep Disorders',
  'Chronic Pain',
  'Medical Trauma',
  'Domestic Violence',
  'Sexual Abuse',
  'Child Abuse',
];

export const TREATMENT_ORIENTATIONS = [
  'Cognitive Behavioral Therapy (CBT)',
  'Dialectical Behavior Therapy (DBT)',
  'Acceptance and Commitment Therapy (ACT)',
  'Psychodynamic Therapy',
  'Humanistic/Person-Centered Therapy',
  'Gestalt Therapy',
  'Solution-Focused Brief Therapy',
  'Narrative Therapy',
  'Family Systems Therapy',
  'Emotionally Focused Therapy (EFT)',
  'Eye Movement Desensitization and Reprocessing (EMDR)',
  'Mindfulness-Based Cognitive Therapy',
  'Interpersonal Therapy',
  'Motivational Interviewing',
  'Trauma-Focused CBT',
  'Play Therapy',
  'Art Therapy',
  'Music Therapy',
  'Somatic Therapy',
  'Integrative Approach',
];

export const MODALITIES = [
  'Individual Therapy',
  'Group Therapy',
  'Couples Therapy',
  'Family Therapy',
  'Online/Telehealth',
  'In-Person',
  'Intensive Outpatient',
  'Workshops',
  'Support Groups',
];

export const AGE_GROUPS = [
  'Children (5-12)',
  'Adolescents (13-17)',
  'Young Adults (18-25)',
  'Adults (26-64)',
  'Seniors (65+)',
];

export const LANGUAGES_EXTENDED = [
  'English',
  'Spanish',
  'French',
  'German',
  'Italian',
  'Portuguese',
  'Dutch',
  'Russian',
  'Polish',
  'Turkish',
  'Arabic',
  'Hebrew',
  'Hindi',
  'Urdu',
  'Bengali',
  'Tamil',
  'Telugu',
  'Gujarati',
  'Punjabi',
  'Marathi',
  'Mandarin Chinese',
  'Cantonese',
  'Japanese',
  'Korean',
  'Vietnamese',
  'Thai',
  'Tagalog',
  'Indonesian',
  'Malay',
];

export const ETHNICITIES_SERVED = [
  'African American/Black',
  'Asian American',
  'Caucasian/White',
  'Hispanic/Latino',
  'Native American',
  'Pacific Islander',
  'Middle Eastern',
  'Mixed Race/Multiracial',
  'South Asian',
  'East Asian',
  'Southeast Asian',
  'Caribbean',
  'African',
  'European',
  'Jewish',
  'Muslim',
  'All Ethnicities',
];